version: '3.3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: life
      POSTGRES_PASSWORD: lifeistooshort
      POSTGRES_USER: lifesupport
    ports:
      - "5432:5432"

